# Generated by Django 5.1 on 2024-10-28 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_item_starting_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='starting_price',
        ),
        migrations.AddField(
            model_name='auction',
            name='starting_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
