# Generated by Django 5.1 on 2024-10-28 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_item_starting_price_auction_starting_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='owner_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='owner_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
