# Generated by Django 5.1 on 2024-10-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auction_owner_id_item_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='status',
            field=models.CharField(default='PENDING', max_length=255),
        ),
    ]
