# Generated by Django 5.1 on 2024-10-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_reserve_price_auction_bid_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='reserve_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
