# Generated by Django 5.1 on 2024-10-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auction_reserve_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='winner_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
