# Generated by Django 5.1 on 2024-10-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='auction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('topup', 'Top-Up'), ('withdraw', 'Withdraw'), ('purchase', 'Purchase')], max_length=10),
        ),
    ]
